@baseUrl = http://localhost:3001

GET {{baseUrl}}/api/pokemon/
###
GET {{baseUrl}}/api/pokemon/1
###
POST {{baseUrl}}/api/pokemon/squirtle
###
POST {{baseUrl}}/api/pokemon/rayquaza
###
DELETE {{baseUrl}}/api/pokemon/5