@baseUrl = http://localhost:5000
@jwtToken = 'JWT_SECRET'
GET {{baseUrl}}/api/pokemon/
###
GET {{baseUrl}}/api/pokemon/1
###
POST {{baseUrl}}/api/pokemon/squirtle
###
POST {{baseUrl}}/api/pokemon/rayquaza
###
POST {{baseUrl}}/api/pokemon/pichu
###
DELETE {{baseUrl}}/api/pokemon/5
###
GET {{baseUrl}}/api/pokemon/search/squirtle

###
POST {{baseUrl}}/api/auth/
Content-Type: application/json

{
    "email": "pedro@gmail.com",
    "password": "admin"
}

###
POST {{baseUrl}}/api/user 
Content-Type: application/json

{
    "email": "pedro@gmail.com",
    "password": "admin",
    "name": "admin"
}

###

GET {{baseUrl}}/api/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoicGVkcm9AZ21haWwuY29tIiwiaWF0IjoxNzMxNDU0ODQ2LCJleHAiOjE3MzE0NTg0NDYsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6MzAwMCJ9.r6Y4d0YqISaL_3LEjQEeCoWYeeYYywQ9F4afgFLX-BE
